"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.guestList = void 0;
let guestList = ["Hassan", "Hussain", "Ahmad", "Ali", "Umar", "Usman"];
exports.guestList = guestList;
console.log(`Assalamualaikum ${guestList[0]} \n You are invited to a dinner at my house. Please confirm your availibility.`);
console.log(`Assalamualaikum ${guestList[1]} \n You are invited to a dinner at my house. Please confirm your availibility.`);
console.log(`Assalamualaikum ${guestList[2]} \n You are invited to a dinner at my house. Please confirm your availibility.`);
console.log(`Assalamualaikum ${guestList[3]} \n You are invited to a dinner at my house. Please confirm your availibility.`);
console.log(`Assalamualaikum ${guestList[4]} \n You are invited to a dinner at my house. Please confirm your availibility.`);
