document.write(`<H1> "Rules for naming JS variables" </H1><br>`)
document.write(`Variable names can only contain Alphabats, Numbers, $ & _ . For example $my_1stVariable.<br>`)
document.write(`Variables must begin with a $, _ or letter. For example $name, _name or name<br>`)
document.write(`Variable names are case sensitive<br>`)
document.write(`Variable names should not be JS keywords`)